In [24]:
import numpy as np
import math 
import qutip as qt

In [25]:
A=qt.rand_herm(4,1).full()

In [26]:
A

array([[ 0.33913946+0.j        , -0.06220078+0.04649991j,
         0.28905076-0.01358472j, -0.31678594-0.07683136j],
       [-0.06220078-0.04649991j,  0.87560224+0.j        ,
         0.25490048+0.06796975j, -0.22763731-0.020448j  ],
       [ 0.28905076+0.01358472j,  0.25490048-0.06796975j,
         0.        +0.j        ,  0.3648712 -0.91743068j],
       [-0.31678594+0.07683136j, -0.22763731+0.020448j  ,
         0.3648712 +0.91743068j,  0.81060554+0.j        ]])

In [32]:
np.set_printoptions(precision=4, suppress = True)

In [33]:
A @ A @ A @ A - (A @ A @ A @ A).T.conj()

array([[ 0.+0.j,  0.-0.j, -0.+0.j,  0.+0.j],
       [ 0.-0.j,  0.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j, -0.+0.j,  0.-0.j, -0.+0.j],
       [-0.+0.j, -0.+0.j,  0.+0.j,  0.+0.j]])

In [22]:
A = np.random.random((4, 4))+*np.random.random((4, 4))

NameError: name 'j' is not defined

In [14]:
A

array([[0.71161532, 0.51897553, 0.57043842, 0.32544563],
       [0.849258  , 0.58824014, 0.89129835, 0.02951041],
       [0.80827633, 0.39676733, 0.46007702, 0.59611441],
       [0.68920974, 0.73138838, 0.95368586, 0.93760929]])

In [15]:
sym_A = A + A.transpose()

In [16]:
sym_A

array([[1.42323064, 1.36823354, 1.37871476, 1.01465537],
       [1.36823354, 1.17648028, 1.28806568, 0.76089879],
       [1.37871476, 1.28806568, 0.92015404, 1.54980027],
       [1.01465537, 0.76089879, 1.54980027, 1.87521857]])

In [17]:
sym_A @ sym_A

array([[6.82802837, 6.10493686, 6.56574686, 6.52460896],
       [6.10493686, 5.49424901, 5.76624762, 5.70656401],
       [6.56574686, 5.76624762, 6.8085319 , 6.71127718],
       [6.52460896, 5.70656401, 6.71127718, 7.52681807]])

In [18]:
sym_A @ sym_A @ sym_A

array([[33.74336016, 29.94635547, 33.43080233, 33.98399891],
       [29.94635547, 26.58627826, 29.6437906 , 30.01256136],
       [33.43080233, 29.6437906 , 33.14563503, 34.18647735],
       [33.98399891, 30.01256136, 34.18647735, 35.4779154 ]])

In [19]:
sym_A @ sym_A @ sym_A @ sym_A

array([[169.57177949, 150.31954635, 168.52523967, 172.56251976],
       [150.31954635, 133.27151076, 149.32268402, 152.8367646 ],
       [168.52523967, 149.32268402, 167.75599144, 171.952899  ],
       [172.56251976, 152.8367646 , 171.952899  , 176.82962644]])